"""Export command for Doushi CLI (export)."""

import json
from pathlib import Path
import typer

from doushi.client import DoushiClient, DoushiAPIError
from doushi.templates import (
    DOCKERFILE_TEMPLATE,
    FASTAPI_SERVE_TEMPLATE,
    REQUIREMENTS_TXT_TEMPLATE,
    generate_export_readme,
)
from doushi.ui import (
    console,
    print_error_panel,
    print_success,
)

export_app = typer.Typer(help="Export model artifacts and standalone Python serving code.")


@export_app.command(name="export")
def export_model(
    project_id: str = typer.Argument(..., help="Unique ID of the project to export"),
    out_dir: Path = typer.Option(
        Path("./doushi-model-bundle"),
        "--out",
        "-o",
        help="Directory where export artifacts will be saved",
    ),
) -> None:
    """Download project code, metadata, Dockerfile, and FastAPI microservice."""
    client = DoushiClient()
    client.check_auth_or_exit()

    with console.status(f"[bold cyan]Exporting project {project_id}...[/bold cyan]"):
        try:
            p = client.get_project(project_id)
        except DoushiAPIError as e:
            print_error_panel("Export Failed", e.message, status_code=e.status_code)
            raise typer.Exit(code=1)

    out_dir.mkdir(parents=True, exist_ok=True)
    project_name = p.get("name", "Doushi Project")

    # 1. Metadata and training pipeline
    with open(out_dir / "metadata.json", "w", encoding="utf-8") as f:
        json.dump(p, f, indent=2, default=str)

    code_content = p.get("generated_code") or p.get("code") or "# Training pipeline code generated by Doushi\n"
    with open(out_dir / "pipeline.py", "w", encoding="utf-8") as f:
        f.write(code_content)

    # 2. Serving microservice & deployment files
    with open(out_dir / "serve.py", "w", encoding="utf-8") as f:
        f.write(FASTAPI_SERVE_TEMPLATE)

    with open(out_dir / "Dockerfile", "w", encoding="utf-8") as f:
        f.write(DOCKERFILE_TEMPLATE)

    with open(out_dir / "requirements.txt", "w", encoding="utf-8") as f:
        f.write(REQUIREMENTS_TXT_TEMPLATE)

    # 3. Local deployment README
    with open(out_dir / "README.md", "w", encoding="utf-8") as f:
        f.write(generate_export_readme(project_id=project_id, project_name=project_name))

    console.print("\n")
    print_success(f"Project exported successfully to [bold cyan]{out_dir}[/bold cyan]!")
    console.print("\n[dim]Files created:[/dim]")
    console.print(f"  ├── {out_dir}/pipeline.py")
    console.print(f"  ├── {out_dir}/serve.py")
    console.print(f"  ├── {out_dir}/Dockerfile")
    console.print(f"  ├── {out_dir}/requirements.txt")
    console.print(f"  └── {out_dir}/metadata.json\n")
