"""Standalone boilerplate templates for model exports."""

FASTAPI_SERVE_TEMPLATE = '''"""
Standalone FastAPI Serving Microservice for Doushi Model
Generated by Doushi CLI (https://doushi.ai)
"""

import os
import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Any, Dict, List, Union

app = FastAPI(title="Doushi Model Serving API", version="1.0.0")

MODEL_PATH = os.getenv("MODEL_PATH", "model.pkl")
model = None

@app.on_event("startup")
def load_model():
    global model
    if os.path.exists(MODEL_PATH):
        model = joblib.load(MODEL_PATH)
        print(f"Loaded model from {MODEL_PATH}")
    else:
        print(f"Warning: {MODEL_PATH} not found. Place your model.pkl in this directory.")

class PredictRequest(BaseModel):
    data: Union[Dict[str, Any], List[Dict[str, Any]]]

@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": model is not None}

@app.post("/predict")
def predict(req: PredictRequest):
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    try:
        if isinstance(req.data, list):
            df = pd.DataFrame(req.data)
        else:
            df = pd.DataFrame([req.data])
        predictions = model.predict(df)
        return {"predictions": predictions.tolist()}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Prediction error: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

DOCKERFILE_TEMPLATE = '''# Production Container for Doushi Exported Model
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python", "serve.py"]
'''

REQUIREMENTS_TXT_TEMPLATE = '''fastapi>=0.110.0
uvicorn>=0.28.0
pydantic>=2.0.0
pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.4.0
xgboost>=2.0.0
joblib>=1.3.0
'''


def generate_export_readme(project_id: str, project_name: str) -> str:
    """Generate Markdown README instructions for an exported bundle."""
    return f"""# Exported Model Bundle - {project_name}

Project ID: `{project_id}`  
Generated by: [Doushi.ai](https://doushi.ai)

## 📦 Contents:
- `pipeline.py`: Full autonomous scikit-learn / XGBoost training script.
- `serve.py`: Production-ready FastAPI inference microservice.
- `Dockerfile`: Standalone deployment container.
- `metadata.json`: Model metrics, evaluation scores, and hyperparameters.

## 🚀 How to Run Locally:
```bash
pip install -r requirements.txt
python serve.py
```

Then test with:
```bash
curl -X POST http://localhost:8000/predict \\
  -H "Content-Type: application/json" \\
  -d '{{"data": {{"feature_1": 10, "feature_2": 20}}}}'
```
"""
